// <auto-generated />
using System;
using Asp.Net_Exercise_03.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asp.Net_Exercise_03.Migrations
{
    [DbContext(typeof(PartyDbContext))]
    partial class PartyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Asp.Net_Exercise_03.DataBase.AssignParty", b =>
                {
                    b.Property<int>("assign_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("party_id")
                        .HasColumnType("int");

                    b.Property<int?>("product_id")
                        .HasColumnType("int");

                    b.HasKey("assign_id");

                    b.HasIndex("party_id");

                    b.HasIndex("product_id");

                    b.ToTable("assign_party");
                });

            modelBuilder.Entity("Asp.Net_Exercise_03.DataBase.Party", b =>
                {
                    b.Property<int>("party_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("party_name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("party_id");

                    b.HasIndex("party_name")
                        .IsUnique()
                        .HasFilter("[party_name] IS NOT NULL");

                    b.ToTable("party");
                });

            modelBuilder.Entity("Asp.Net_Exercise_03.DataBase.Product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("product_name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("product_id");

                    b.HasIndex("product_name")
                        .IsUnique()
                        .HasFilter("[product_name] IS NOT NULL");

                    b.ToTable("product");
                });

            modelBuilder.Entity("Asp.Net_Exercise_03.DataBase.ProductRate", b =>
                {
                    b.Property<int>("rate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date_of_rate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("rate")
                        .HasColumnType("int");

                    b.HasKey("rate_id");

                    b.HasIndex("product_id");

                    b.ToTable("rate");
                });

            modelBuilder.Entity("Asp.Net_Exercise_03.DataBase.AssignParty", b =>
                {
                    b.HasOne("Asp.Net_Exercise_03.DataBase.Party", "party")
                        .WithMany()
                        .HasForeignKey("party_id");

                    b.HasOne("Asp.Net_Exercise_03.DataBase.Product", "product")
                        .WithMany()
                        .HasForeignKey("product_id");
                });

            modelBuilder.Entity("Asp.Net_Exercise_03.DataBase.ProductRate", b =>
                {
                    b.HasOne("Asp.Net_Exercise_03.DataBase.Product", "product")
                        .WithMany()
                        .HasForeignKey("product_id");
                });
#pragma warning restore 612, 618
        }
    }
}
